### ISSUE TITLE
[Question] Registering components via an UID+Size vs Type.

### ISSUE THREAD

**Issue by LouChiSoft** [Indra-db/Flecs-Rust#177]
Hi, I am in the planning stage of a Rust written ECS game engine. As part of that enigne I want to implement a scripting language that the user will write with instead of directly writing in Rust. If I understand the C API correctly, components are registered in a world with a unique ID rather than a concrete typing e.g. `Position`. I was wondering if this functionality is/could be exposed in the Rust version?

Hopefully my plan to save a UID and size for each component defined in the scripting language when it's compiled would be enough to pass to the Rust side of the code and register the component the first time that it is added to an entity in a given World.

I realise that this might be a bit early to ask since the project is in the experimental phase but I figured I would ask anyway.

**Comment by Indra-db** [comment]
Hi @LouChiSoft , the project isn't in an experimental phase, but the API is!

Sounds like you want to define dynamic, runtime components, which is possible since recently with meta addon being added.

see examples: 
* https://github.com/Indra-db/Flecs-Rust/blob/main/flecs_ecs/examples/flecs/reflection/reflection_runtime_component.rs
* https://github.com/Indra-db/Flecs-Rust/blob/main/flecs_ecs/examples/flecs/reflection/reflection_runtime_nested_component.rs

If I understand correctly and you are creating your own scripting language, then I would highly suggest you to also check out flecs script
* https://www.flecs.dev/flecs/md_docs_2FlecsScript.html

and the examples here:
* https://github.com/Indra-db/Flecs-Rust/tree/main/flecs_ecs/examples/flecs/script

you can also look at the underlying flecs script implementation in Flecs C repo. 

I will ping Sander to see if he has anything to add to this.

**Comment by LouChiSoft** [comment]
Thanks, runtime registration is what I was looking for. I am looking to do my own scripting language and I did see that Flecs has a scripting language, but in this scenario (assuming everything goes well) the scripting language is gonna cover way more than just writing Flecs scenes. So I figured I would build it from scratch to support all the features I want to support

**Comment by Indra-db** [comment]
@LouChiSoft Yes indeed, Flecs script has the parsing support to create components, maybe you could branch from there or take inspiration on how it achieves it.
