### ISSUE TITLE
Remove the prelude? 😅

### ISSUE THREAD

**Issue by andrewgazelka** [Indra-db/Flecs-Rust#203]
Thoughts on removing the prelude? 

- IntelliJ auto import does not work with it (nice for copilot/supermaven suggestions)
- many libraries do not have a prelude (see `clap`)
- some consider `::*` an anti-pattern
- really idk honestly would like some people who know idiomatic rust to chime in 

<img width="654" alt="image" src="https://github.com/user-attachments/assets/3078888d-1859-40ff-acc4-493484a3c99f">

**Comment by andrewgazelka** [comment]
@james-j-obrien

**Comment by james-j-obrien** [comment]
One of the reasons preludes became popular is it can (depending on tooling) make it easier for auto-complete to find trait methods that otherwise wouldn't be in scope, especially for bigger crates like an ECS. You'd have to test in each popular IDE to see how much that holds up today.

When I test in VSCode it prefers the core import in flecs, but only offers the prelude in bevy. Not sure how this is determined by rust analyzer or if there's any annotations that could make IntelliJ more clearly prefer one module. It's also possible to only expose the types in the prelude so there's no alternative path to trip it up.

Personally if a crate upstream of me has a common type I want to avoid conflicting with it regardless of whether or not I actually use it in most files in order to avoid any confusion between the two potential variants. In that case ::* imports aren't particularly problematic (except in the rare case when two upstream crates conflict) and the using blocks at the top of every file end up as a source of merge conflicts, most modern IDEs will be able to tell you where a type is coming from if you ever need to check.

This is an unfortunate edge case, in general people can freely choose the style they prefer.

**Comment by andrewgazelka** [comment]
ok closing since it still seems standard 🥲
